### ISSUE TITLE
Make it possible to assign a custom profile identifier to each profile

### ISSUE THREAD

**Issue by robertobernabe** [woernsn/openEpcQrGen#1]
If you are adding multiple profiles with the same Account Name (which is in the end the receiver name .e.g. John Doe), you only can distinguish multiple accounts by the IBAN.
It would be better if you could assign a custom profile name for it, like `My ING DIBA bank account`.

**Comment by woernsn** [comment]
Done with version `1.1`.
Now there is a `Profile Name` for displaying purposes and `Account Holder` for the actual name of the account holder.
See https://github.com/woernsn/openEpcQrGen/commit/b247745093199565e6fd7fdfb419a4e6f706d992
